version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/backend/js/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/frontend/angular/hlp/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"
    target-branch: "develop"
