version: "3"

services:
  backend:
    image: hlp-backend-dev
    build:
      context: backend/js/
      dockerfile: Dockerfile.dev
    networks:
      - hlp-network-dev
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      BACKEND_PORT: 8080
      JWT_SECRET: ${JWT_SECRET:?}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      EMAIL_DEBUG: ${EMAIL_DEBUG}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
    volumes:
      - "./backend/js:/usr/src/app"
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    networks:
      - hlp-network-dev
    ports:
      - 27017:27017
    volumes:
      - ./backend/mongo/mongod.conf:/etc/mongod.conf:ro
      - ./backend/mongo/setup/:/docker-entrypoint-initdb.d/:ro
      - hlp-mongo-db-data:/data/db/ # Not working on windows unless you do the workaround
      - ./backend/mongo/data/log/:/var/log/mongodb/
      - ./backend/mongo/dbshell:/home/mongodb/
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: root # admin username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD} # admin password
    command: ["-f", "/etc/mongod.conf"]

networks:
  hlp-network-dev:

volumes:
  hlp-mongo-db-data:
