version: '3'

services: 
    backend:
        image: hlp-backend
        build: server/
        networks: 
            - hlp-network
        environment: 
            NODE_ENV: production
            BACKEND_PORT: 8080
            JWT_SECRET: ${JWT_SECRET}
            MONGO_DB_NAME: ${MONGO_DB_NAME}
            MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
            MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
        restart: always
        depends_on: 
            - mongo
    
    nginx:
        build: .
        ports:
            - ${HOST_PORT}:80
        networks: 
            - hlp-network
        depends_on: 
            - backend
    
    mongo:
        image: mongo:4
        networks: 
            - hlp-network
        volumes: 
            - ./mongo/mongod.conf:/etc/mongod.conf:ro
            - ./mongo/setup/:/docker-entrypoint-initdb.d/:ro
            - hlp-mongo-db-data:/data/db/                           # Not working on windows unless you do the workaround
            - ./mongo/data/log/:/var/log/mongodb/
            - ./mongo/dbshell:/home/mongodb/
        environment:
            MONGO_INITDB_USERNAME: ${MONGO_DB_USERNAME}
            MONGO_INITDB_PASSWORD: ${MONGO_DB_PASSWORD}
            MONGO_INITDB_DATABASE:  ${MONGO_DB_NAME}
            MONGO_INITDB_ROOT_USERNAME: root                        # admin username
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}   # admin password
        command: ["-f", "/etc/mongod.conf"]


networks: 
    hlp-network:

volumes: 
    hlp-mongo-db-data:
