version: '3'

services: 
    hlp-backend:
        build: server/
        networks: 
            - hlp-network
        environment: 
            BACKEND_PORT: 8080
        restart: always
    
    nginx:
        build: .
        ports:
            - ${HOST_PORT}:80
        networks: 
            - hlp-network

networks: 
    hlp-network:
    
