version: "3"

services:
  backend:
    image: hlp-backend
    build: backend/js/
    networks:
      - hlp-network
    environment:
      NODE_ENV: production
      BACKEND_PORT: 8080
      JWT_SECRET: ${JWT_SECRET:?err}
      MONGO_DB_NAME: ${MONGO_DB_NAME:?err}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME:?err}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD:?err}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      EMAIL_DEBUG: ${EMAIL_DEBUG:-false}
    restart: always
    depends_on:
      - mongo

  nginx:
    image: hlp-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - ${HOST_PORT}:80
    networks:
      - hlp-network
    depends_on:
      - backend

  mongo:
    image: hlp-db
    build: backend/mongo/
    networks:
      - hlp-network
    volumes:
      - hlp-mongo-db-data:/data/db/
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_DB_USERNAME:?err}
      MONGO_INITDB_PASSWORD: ${MONGO_DB_PASSWORD:?err}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:?err}
      MONGO_INITDB_ROOT_USERNAME: root # admin username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD:?err} # admin password

networks:
  hlp-network:

volumes:
  hlp-mongo-db-data:
