name: Update Passwords scores

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 15 * *


jobs:
  update:
    name: Update passwords scores
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('backend/js/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        working-directory: backend/js
        run: npm ci
      - name: Build
        working-directory: backend/js
        run: npm build
      - name: Run update script
        working-directory: backend/js
        run: npm run update-psw
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: backend/js/app/game/passwords/
          branch: master
          message: 'Update password scores through GitHub Actions automation'
          push: true
