name: Telegram Notifier

on:
  issue_comment:
    types: created
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: created
  push:

jobs:
  notify:
    name: Telegram Notification
    runs-on: ubuntu-latest

    steps:
    - name: Call Telegram Bridge
      uses: GokulDas027/TelegramBridge@master
      if: always()
      with:
        chat: ${{ secrets.TELEGRAM_CHAT_ID }} # save your chat id at settings/secrets with name: TELEGRAM_CHAT_ID
        token: ${{ secrets.TELEGRAM_BOT_ID }} # savethe bot token at settings/secrets with name: TELEGRAM_BOT_ID
        status: ${{ job.status }} # don't change
        event: ${{ github.event_name }} # don't change
        actor: ${{ github.actor }} # don't change
